export const songs = [
    {
      id:1,
      title: 'Faded',
      artist: 'Alan Walker',
      artwork: require('./songs/images/faded.jpg'),
      url: require('./songs/faded.mp3'),
      genre: 'Electronic',
    },
    {
      id:2,
      title: 'Head Light',
      artist: 'Alan Walker',
      artwork: require('./songs/images/headlight.jpg'),
      url: require('./songs/headlight.mp3'),
      genre: 'Electronic',
    },
    {
      id:3,
      title: 'Attention',
      artist: 'Charlie Puth',
      artwork: require('./songs/images/attention.jpg'),
      url: require('./songs/attention.mp3'),
      genre: 'Pop',
    },
    {
      id:4,
      title: 'On My Way',
      artist: 'Alan Walker',
      artwork: require('./songs/images/on_my_way.jpg'),
      url: require('./songs/on_my_way.mp3'),
      genre: 'Electronic',
    },
    {
      id:5,
      title: 'Dreamers',
      artist: 'Jung Kook',
      artwork: require('./songs/images/dreamers.jpg'),
      url: require('./songs/dreamers.mp3'),
      genre: 'K-Pop',
    },
    {
      id:6,
      title: 'Wavin Flag',
      artist: 'K’Naan',
      artwork: require('./songs/images/wavinflag.jpg'),
      url: require('./songs/wavin_flag.mp3'),
      genre: 'World',
    },
    {
      id:7,
      title: 'Rockabye',
      artist: 'Clean Bandit',
      artwork: require('./songs/images/rockabye.jpg'),
      url: require('./songs/rockabye.mp3'),
      genre: 'Pop',
    },
    {
      id:8,
      title: "We Don’t Talk Anymore",
      artist: 'Charlie Puth',
      artwork: require('./songs/images/wdtam.jpg'),
      url: require('./songs/no_talk.mp3'),
      genre: 'Pop',
    },
    {
      id:9,
      title: 'See You Again',
      artist: 'Charlie Puth',
      artwork: require('./songs/images/without_my_friend.jpg'),
      url: require('./songs/see_you_again.mp3'),
      genre: 'Pop',
    },
    {
      id:10,
      title: 'Dark Side',
      artist: 'Sabrina',
      artwork: require('./songs/images/darkside.jpg'),
      url: require('./songs/darkside.mp3'),
      genre: 'Electronic',
    },
  ];
  